[package]
name = "helixdb-explorer"
version = "0.3.1"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "helixdb_explorer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-opener = "2"
tauri-plugin-http = "2"
tauri-plugin-clipboard-manager = "2"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
reqwest = { version = "0.12", features = ["blocking", "json"] }
window-vibrancy = "0.7.1"
tempfile = "3"
regex = "1"
dirs = "5"
helix-db = { git = "https://github.com/HelixDB/helix-db", features = ["compiler", "server"] }
sonic-rs = "0.5"
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
rand = "0.8"
heed3 = "0.22.0"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

